version: '3'
services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ft_min_word_len=1 --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  app:
    build: .
    command:
      - bin/start_server.sh
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_DB_HOST: db
      RAILS_LOG_TO_STDOUT: 'true'
    ports:
      - '3000:3000'
    depends_on:
      - db