variable "project_id" {}
variable "sys_name" {}
variable "env" {}
variable "region" {}
variable "db_user_name" {}
variable "db_user_pass" {}
variable "db_machine_type" {}
variable "db_disk_size" {}
variable "vpc_net_id" {}
variable "priv_vpc_conn" {}
